version: '3'

services:
  jsdoc_container:
    build:
      context: ../
      dockerfile: ./docker/jsdocContainer/Dockerfile
    tty: true
    volumes:
      # for test
      #      - ../secret:/app/secret
      #      - ../service:/app/src/service
      # for xdevkit
      #      - ../../../../secret:/app/secret
      #      - ../../../../service:/app/src/service
      - ${SECRET_PATH}:/app/secret
      - ${SERVICE_PATH}:/app/src/service
      - ../src/setting:/app/src/setting
      - ../build:/app/src/build

    command: sh -c "git config --global user.name ${GIT_USER_NAME} && git config --global user.email ${GIT_USER_EMAIL} && git config --global remote.origin.url ${GIT_REPOSITORY_URL} && cd src && mkdir -p /root/.ssh/ && cp ./setting/jsdoc_ssh_config /root/.ssh/config && yarn run ${JSDOC_COMMAND}"

