version: '3'

services:
  jsdoc_container:
    container_name: jsdoc-container
    build:
      context: ../
      dockerfile: ./docker/jsdocContainer/Dockerfile
    tty: true
    volumes:
      - ../.git/:/app/.git
      - ../src/setting:/app/src/setting
      - ../service:/app/src/service
      - ../build:/app/src/build
    command: sh -c "git config --global user.name ${GIT_USER_NAME} && git config --global user.email ${GIT_USER_EMAIL} && cd src && mkdir -p /root/.ssh/ && cp ./setting/jsdoc_ssh_config /root/.ssh/config && yarn run ${JSDOC_COMMAND}"

