version: '3'

services:
  eslit_container:
    container_name: jsdoc-container
    build:
      context: ../
      dockerfile: ./docker/jsdocContainer/Dockerfile
    tty: true
    volumes:
      - ../src/setting:/app/setting:ro
      - ../service:/app/service
    command: sh -c "yarn jsdoc ${JSDOC_COMMAND}"


