version: '3'

services:
  jsdoc_container:
    container_name: jsdoc-container
    build:
      context: ../
      dockerfile: ./docker/jsdocContainer/Dockerfile
    tty: true
    volumes:
      - ../.git/:/app/.git
      - ../src/setting:/app/src/setting
      - ../service:/app/src/service
      - ../build:/app/src/build
    command: sh -c "git remote add origin git@github.com:/autoaim-jp/xdevkit-jsdoc && cd src && yarn run ${JSDOC_COMMAND}"

